const svg = document.getElementById('automataCanvas');
const nodesLayer = document.getElementById('nodesLayer');
const edgesLayer = document.getElementById('edgesLayer');
const draftLayer = document.getElementById('draftLayer');
const canvasWrap = document.getElementById('canvasWrap');
const canvasEmpty = document.getElementById('canvasEmpty');
let nodes = [], edges = [], selectedNode = null, selectedEdge = null, nodeCounter = 0, edgeCounter = 0;
let mode = 'select', linkSource = null, dragging = null, edgeDragging = null, simulation = null, zoom = 1;
let machines = [], activeMachine = 0, playbackTimer = null;
let history = [], future = [], restoringHistory = false, testedResults = [];
let viewSettings = JSON.parse(localStorage.getItem('automata-lab-view-settings') || '{"grid":true,"labels":true,"checker":true,"legend":true}');
function getAlphabet() { return (document.getElementById('alphabetInput')?.value || '').split(/[;,\s]+/).map(symbol => symbol.trim()).filter(Boolean).filter(symbol => symbol !== 'eps'); }

const palette = document.querySelectorAll('.palette-item');
palette.forEach(item => item.addEventListener('dragstart', event => event.dataTransfer.setData('node-type', item.dataset.nodeType)));
canvasWrap.addEventListener('dragover', event => event.preventDefault());
canvasWrap.addEventListener('drop', event => {
  event.preventDefault();
  const type = event.dataTransfer.getData('node-type');
  if (type) { const point = pointerPosition(event); addNode(type, point.x, point.y); }
});

initMachines();
function initMachines() {
  try { machines = JSON.parse(localStorage.getItem('automata-lab-machines') || '[]'); } catch (error) { machines = []; }
  if (!machines.length) { machines = [{ name: 'Machine 1', nodes: [], edges: [], nodeCounter: 0, edgeCounter: 0 }]; defaultGraph(); persistMachine(); }
  else loadMachine(0);
  renderTabs();
}
function persistMachine() { machines[activeMachine] = { ...machines[activeMachine], nodes, edges, nodeCounter, edgeCounter, alphabet: getAlphabet(), testedResults }; localStorage.setItem('automata-lab-machines', JSON.stringify(machines)); }
function loadMachine(index) { activeMachine = index; const machine = machines[index]; nodes = machine.nodes || []; edges = machine.edges || []; nodeCounter = machine.nodeCounter || nodes.length; edgeCounter = machine.edgeCounter || edges.length; selectedNode = null; selectedEdge = null; simulation = null; testedResults = machine.testedResults || []; history = []; future = []; const alphabetInput = document.getElementById('alphabetInput'); if (alphabetInput) alphabetInput.value = (machine.alphabet || ['a', 'b']).join(', '); render(); renderTabs(); }
function renderTabs() { const tabs = document.getElementById('machineTabs'); if (!tabs) return; tabs.innerHTML = machines.map((machine, index) => `<button class="machine-tab${index === activeMachine ? ' active' : ''}" data-machine="${index}">${machine.name}<span class="tab-close" data-close="${index}">${index ? 'x' : ''}</span></button>`).join('') + '<button class="machine-tab" id="addTab">+</button>'; tabs.querySelectorAll('[data-machine]').forEach(tab => tab.addEventListener('click', event => { if (event.target.dataset.close) { event.stopPropagation(); closeMachine(Number(event.target.dataset.close)); } else { persistMachine(); loadMachine(Number(tab.dataset.machine)); } })); document.getElementById('addTab').addEventListener('click', createMachine); }
function createMachine() { persistMachine(); machines.push({ name: `Machine ${machines.length + 1}`, nodes: [], edges: [], nodeCounter: 0, edgeCounter: 0, alphabet: ['a', 'b'] }); loadMachine(machines.length - 1); persistMachine(); }
function closeMachine(index) { if (machines.length === 1) return; machines.splice(index, 1); activeMachine = Math.max(0, Math.min(activeMachine, machines.length - 1)); loadMachine(activeMachine); persistMachine(); }
function defaultGraph() {
  addNode('start', 210, 315, false); addNode('normal', 465, 315, false); addNode('accept', 720, 315, false);
  addEdge(nodes[0].id, nodes[1].id, 'a'); addEdge(nodes[1].id, nodes[1].id, 'b'); addEdge(nodes[1].id, nodes[2].id, 'a');
  render();
}
function pointerPosition(event) {
  const rect = svg.getBoundingClientRect();
  return { x: ((event.clientX - rect.left) / rect.width) * 1000, y: ((event.clientY - rect.top) / rect.height) * 680 };
}
function nodeAt(point, excludedId = null) { return nodes.find(node => node.id !== excludedId && Math.hypot(node.x - point.x, node.y - point.y) <= 48); }
function addNode(type, x, y, redraw = true) {
  const id = `q${nodeCounter++}`;
  const node = { id, label: type === 'trap' ? 'qD' : id, type, x, y };
  nodes.push(node); selectNode(node.id); if (redraw) render(); return node;
}
function addEdge(from, to, label = 'a') { const edge = { id: `e${edgeCounter++}`, from, to, label, offset: 0 }; edges.push(edge); return edge; }
function nodeById(id) { return nodes.find(node => node.id === id); }
function render() {
  canvasEmpty.classList.toggle('hidden', nodes.length > 0);
  renderEdges(); renderNodes(); renderInspector(); renderFormal(); renderMachineType(); renderTestedResults(); persistMachine();
  recordHistory();
  updateHistoryButtons();
  applyViewSettings();
}
function applyViewSettings() { document.querySelector('.canvas-grid')?.classList.toggle('settings-hidden', !viewSettings.grid); document.querySelector('.canvas-legend')?.classList.toggle('settings-hidden', !viewSettings.legend); document.getElementById('machineToast')?.classList.toggle('settings-hidden', !viewSettings.checker); document.querySelectorAll('.edge-label').forEach(label => label.classList.toggle('settings-hidden', !viewSettings.labels)); }
function recordHistory() { if (restoringHistory) return; const snapshot = JSON.stringify({ nodes, edges, nodeCounter, edgeCounter }); if (history[history.length - 1] !== snapshot) { history.push(snapshot); future = []; } }
function restoreSnapshot(snapshot) { const state = JSON.parse(snapshot); nodes = state.nodes; edges = state.edges; nodeCounter = state.nodeCounter; edgeCounter = state.edgeCounter; selectedNode = null; selectedEdge = null; restoringHistory = true; render(); restoringHistory = false; }
function undo() { if (history.length < 2) return; future.push(history.pop()); restoreSnapshot(history[history.length - 1]); }
function redo() { if (!future.length) return; const snapshot = future.pop(); history.push(snapshot); restoreSnapshot(snapshot); }
function updateHistoryButtons() { const undoButton = document.getElementById('undoBtn'); const redoButton = document.getElementById('redoBtn'); if (undoButton) undoButton.disabled = history.length < 2; if (redoButton) redoButton.disabled = future.length === 0; }
function renderEdges() {
  edgesLayer.innerHTML = '';
  draftLayer.innerHTML = '';
  edges.forEach(edge => {
    const from = nodeById(edge.from), to = nodeById(edge.to); if (!from || !to) return;
    const same = from.id === to.id;
    let path, labelX, labelY, arrowX, arrowY, arrowDX, arrowDY;
    if (same) { const side = edge.loopSide || 'top'; if (side === 'bottom') { path = `M ${from.x - 20} ${from.y + 13} C ${from.x - 80} ${from.y + 100}, ${from.x + 80} ${from.y + 100}, ${from.x + 20} ${from.y + 13}`; labelX = from.x; labelY = from.y + 78; arrowX = from.x + 20; arrowY = from.y + 13; arrowDX = -60; arrowDY = -87; } else if (side === 'left') { path = `M ${from.x - 13} ${from.y - 20} C ${from.x - 100} ${from.y - 80}, ${from.x - 100} ${from.y + 80}, ${from.x - 13} ${from.y + 20}`; labelX = from.x - 78; labelY = from.y + 4; arrowX = from.x - 13; arrowY = from.y + 20; arrowDX = 87; arrowDY = -60; } else if (side === 'right') { path = `M ${from.x + 13} ${from.y - 20} C ${from.x + 100} ${from.y - 80}, ${from.x + 100} ${from.y + 80}, ${from.x + 13} ${from.y + 20}`; labelX = from.x + 78; labelY = from.y + 4; arrowX = from.x + 13; arrowY = from.y + 20; arrowDX = -87; arrowDY = -60; } else { path = `M ${from.x - 20} ${from.y - 13} C ${from.x - 80} ${from.y - 100}, ${from.x + 80} ${from.y - 100}, ${from.x + 20} ${from.y - 13}`; labelX = from.x; labelY = from.y - 78; arrowX = from.x + 20; arrowY = from.y - 13; arrowDX = -60; arrowDY = 87; } }
    else { const dx = to.x - from.x, dy = to.y - from.y, length = Math.hypot(dx, dy), ux = dx / length, uy = dy / length; const x1 = from.x + ux * 25, y1 = from.y + uy * 25, x2 = to.x - ux * 25, y2 = to.y - uy * 25; const offset = edge.offset || 0, cx = (x1 + x2) / 2 - uy * offset, cy = (y1 + y2) / 2 + ux * offset; path = `M ${x1} ${y1} Q ${cx} ${cy} ${x2} ${y2}`; labelX = (x1 + 2 * cx + x2) / 4; labelY = (y1 + 2 * cy + y2) / 4 - 10; arrowX = x2; arrowY = y2; arrowDX = x2 - cx; arrowDY = y2 - cy; }
    const active = simulation?.activeEdges?.includes(edge.id);
    const activeAccepted = active && simulation?.activeStatus === 'accepted';
    const activeDead = active && simulation?.activeStatus === 'dead';
    const hit = document.createElementNS('http://www.w3.org/2000/svg', 'path'); hit.setAttribute('d', path); hit.setAttribute('class', 'edge-hit'); hit.addEventListener('pointerdown', event => { event.stopPropagation(); edgeDragging = { edge, loop: same }; selectedEdge = edge.id; selectedNode = null; }); hit.addEventListener('click', event => { event.stopPropagation(); editEdge(edge); });
    const line = document.createElementNS('http://www.w3.org/2000/svg', 'path'); line.setAttribute('d', path); line.setAttribute('class', `edge${active ? ' active' : ''}${activeAccepted ? ' accepted' : ''}${activeDead ? ' dead' : ''}`); line.dataset.edgeId = edge.id; line.addEventListener('pointerdown', event => { event.stopPropagation(); edgeDragging = { edge, loop: same }; selectedEdge = edge.id; selectedNode = null; }); line.addEventListener('click', event => { event.stopPropagation(); editEdge(edge); });
    const label = document.createElementNS('http://www.w3.org/2000/svg', 'text'); label.setAttribute('x', labelX); label.setAttribute('y', labelY); label.setAttribute('class', 'edge-label'); label.textContent = edge.label; label.addEventListener('pointerdown', event => { event.stopPropagation(); edgeDragging = { edge, loop: same }; selectedEdge = edge.id; selectedNode = null; }); label.addEventListener('click', event => { event.stopPropagation(); editEdge(edge); });
    const head = document.createElementNS('http://www.w3.org/2000/svg', 'polygon'); head.setAttribute('class', 'edge-arrowhead'); head.setAttribute('points', arrowheadPoints(arrowX, arrowY, arrowDX, arrowDY)); head.setAttribute('fill', activeAccepted ? '#4d9b69' : activeDead ? '#d96d5c' : active ? '#e65f42' : '#25333a'); head.addEventListener('click', event => { event.stopPropagation(); editEdge(edge); });
    edgesLayer.append(hit, line, head, label);
  });
  if (linkSource) drawDraft(linkSource);
}
function arrowheadPoints(x, y, dx, dy) { const length = Math.hypot(dx, dy) || 1; const ux = dx / length, uy = dy / length, size = 9, width = 3.5; return `${x},${y} ${x - ux * size + uy * width},${y - uy * size - ux * width} ${x - ux * size - uy * width},${y - uy * size + ux * width}`; }
function renderNodes() {
  nodesLayer.innerHTML = '';
  nodes.forEach(node => {
    const group = document.createElementNS('http://www.w3.org/2000/svg', 'g');
    const active = simulation?.activeStates?.includes(node.id);
    const activeAccepted = active && simulation?.activeStatus === 'accepted';
    group.setAttribute('class', `node ${node.type}${selectedNode === node.id ? ' selected' : ''}${active ? ' active' : ''}${activeAccepted ? ' accepted' : ''}`); group.setAttribute('transform', `translate(${node.x} ${node.y})`); group.dataset.id = node.id;
    const circle = document.createElementNS('http://www.w3.org/2000/svg', 'circle'); circle.setAttribute('r', 25);
    group.appendChild(circle);
    if (node.type === 'accept') { const ring = document.createElementNS('http://www.w3.org/2000/svg', 'circle'); ring.setAttribute('r', 20); ring.setAttribute('class', 'inner-ring'); group.appendChild(ring); }
    const text = document.createElementNS('http://www.w3.org/2000/svg', 'text'); text.textContent = node.label; group.appendChild(text);
    if (node.type === 'start') { const start = document.createElementNS('http://www.w3.org/2000/svg', 'path'); start.setAttribute('d', 'M -62 0 L -25 0'); start.setAttribute('class', 'start-arrow'); const head = document.createElementNS('http://www.w3.org/2000/svg', 'polygon'); head.setAttribute('class', 'start-arrowhead'); head.setAttribute('points', arrowheadPoints(-25, 0, 1, 0)); head.setAttribute('fill', '#25333a'); group.append(start, head); }
    group.addEventListener('click', event => { event.stopPropagation(); if (mode === 'link') { if (!linkSource) { linkSource = node.id; } else { addEdge(linkSource, node.id, 'a'); linkSource = null; mode = 'select'; updateMode(); } render(); } else selectNode(node.id); });
    group.addEventListener('pointerdown', event => { if (mode === 'link') { linkSource = node.id; group.setPointerCapture(event.pointerId); window.lastPointerEvent = event; renderEdges(); } else { dragging = { node, pointerId: event.pointerId }; group.setPointerCapture(event.pointerId); } });
    group.addEventListener('pointermove', event => { if (dragging?.node.id === node.id) { const point = pointerPosition(event); node.x = Math.max(35, Math.min(965, point.x)); node.y = Math.max(35, Math.min(645, point.y)); document.getElementById('coordinateReadout').textContent = `x ${String(Math.round(node.x)).padStart(3, '0')}   y ${String(Math.round(node.y)).padStart(3, '0')}`; render(); } });
    group.addEventListener('pointerup', event => { if (mode === 'link' && linkSource === node.id) { const target = nodeAt(pointerPosition(event)); if (target) { const edge = addEdge(node.id, target.id, 'a'); selectedEdge = edge.id; selectedNode = null; linkSource = null; mode = 'select'; updateMode(); } } dragging = null; render(); });
    nodesLayer.appendChild(group);
  });
}
function scrollInspectorIntoView() { const panel = document.querySelector('.left-panel'); const inspector = document.getElementById('inspector'); if (!panel || !inspector) return; requestAnimationFrame(() => panel.scrollTo({ top: Math.max(0, inspector.offsetTop - 12), behavior: 'smooth' })); }
function selectNode(id) { selectedNode = id; selectedEdge = null; render(); scrollInspectorIntoView(); }
function renderInspector() {
  const content = document.getElementById('inspectorContent'); const node = nodeById(selectedNode);
  const edge = edges.find(item => item.id === selectedEdge);
  if (edge) { content.className = 'edge-editor'; const options = [...getAlphabet(), 'Σ', 'eps']; content.innerHTML = `<div class="edge-endpoints">${nodeById(edge.from)?.label}  ->  ${nodeById(edge.to)?.label}</div><label class="field-label">TRANSITION LABEL / INPUT SYMBOL</label><select class="field-input" id="edgeLabel">${options.map(symbol => `<option value="${symbol}"${symbol === edge.label ? ' selected' : ''}>${symbol === 'Σ' ? 'Σ (any alphabet symbol)' : symbol}</option>`).join('')}</select><div class="input-note"><code>Σ</code> consumes any one symbol. <code>eps</code> consumes none.</div><div class="edge-editor-actions"><button class="save-edge" id="saveEdge">Update arrow</button><button class="delete-state" id="deleteEdge">Remove arrow</button></div>`; document.getElementById('saveEdge').addEventListener('click', () => { edge.label = document.getElementById('edgeLabel').value; selectedEdge = null; render(); }); document.getElementById('deleteEdge').addEventListener('click', () => { edges = edges.filter(item => item.id !== edge.id); selectedEdge = null; render(); }); return; }
  if (!node) { content.className = 'empty-inspector'; content.innerHTML = '<span class="crosshair">+</span><p>Select a state<br>to inspect it.</p>'; return; }
  content.className = 'inspector-form'; content.innerHTML = `<label class="field-label">STATE NAME</label><input class="field-input" id="stateName" value="${node.label}"><button class="delete-state" id="deleteState">Remove state</button>`;
  document.getElementById('stateName').addEventListener('input', event => { node.label = event.target.value || node.id; renderNodes(); recordHistory(); });
  document.getElementById('deleteState').addEventListener('click', () => { nodes = nodes.filter(item => item.id !== node.id); edges = edges.filter(edge => edge.from !== node.id && edge.to !== node.id); selectedNode = null; render(); });
}
function editEdge(edge) {
  selectedEdge = edge.id; selectedNode = null; render(); scrollInspectorIntoView();
}
function drawDraft(source) { draftLayer.innerHTML = ''; const node = nodeById(source); const point = pointerPosition(window.lastPointerEvent || { clientX: 0, clientY: 0 }); if (!node || !window.lastPointerEvent) return; const path = document.createElementNS('http://www.w3.org/2000/svg', 'path'); path.setAttribute('class', 'draft-edge'); path.setAttribute('d', `M ${node.x} ${node.y} L ${point.x} ${point.y}`); draftLayer.appendChild(path); }
svg.addEventListener('pointermove', event => { window.lastPointerEvent = event; if (linkSource) renderEdges(); if (edgeDragging) { const point = pointerPosition(event), edge = edgeDragging.edge, from = nodeById(edge.from), to = nodeById(edge.to); if (from && to && edgeDragging.loop) { const dx = point.x - from.x, dy = point.y - from.y; edge.loopSide = Math.abs(dx) > Math.abs(dy) ? (dx < 0 ? 'left' : 'right') : (dy < 0 ? 'top' : 'bottom'); renderEdges(); } else if (from && to && from.id !== to.id) { const dx = to.x - from.x, dy = to.y - from.y, length = Math.hypot(dx, dy); edge.offset = Math.round(((point.x - (from.x + to.x) / 2) * (-dy / length)) + ((point.y - (from.y + to.y) / 2) * (dx / length))); renderEdges(); } } });
svg.addEventListener('pointerup', event => {
  if (mode === 'link' && linkSource) {
    const target = nodeAt(pointerPosition(event));
    if (target) {
      const edge = addEdge(linkSource, target.id, 'a');
      selectedEdge = edge.id; selectedNode = null; linkSource = null; mode = 'select'; updateMode();
    } else {
      linkSource = null; mode = 'select'; updateMode();
    }
  }
  edgeDragging = null; render();
});
svg.addEventListener('click', () => { if (mode === 'link') { linkSource = null; mode = 'select'; updateMode(); render(); } else { selectedNode = null; render(); } });

document.getElementById('arrowTool').addEventListener('click', () => { mode = mode === 'link' ? 'select' : 'link'; linkSource = null; updateMode(); render(); });
function updateMode() { const button = document.getElementById('arrowTool'); button.classList.toggle('active', mode === 'link'); document.getElementById('modeLabel').textContent = mode === 'link' ? 'Connect states' : 'Select & move'; }
document.getElementById('newMachineBtn').addEventListener('click', createMachine);
document.getElementById('openBtn').addEventListener('click', () => document.getElementById('openFile').click());
document.getElementById('settingsBtn').addEventListener('click', () => { document.getElementById('showGridSetting').checked = viewSettings.grid; document.getElementById('showLabelsSetting').checked = viewSettings.labels; document.getElementById('showCheckerSetting').checked = viewSettings.checker; document.getElementById('showLegendSetting').checked = viewSettings.legend; document.getElementById('settingsDialog').showModal(); });
document.getElementById('closeSettings').addEventListener('click', () => document.getElementById('settingsDialog').close());
document.querySelectorAll('.settings-options input').forEach(input => input.addEventListener('change', () => { viewSettings = { grid: document.getElementById('showGridSetting').checked, labels: document.getElementById('showLabelsSetting').checked, checker: document.getElementById('showCheckerSetting').checked, legend: document.getElementById('showLegendSetting').checked }; localStorage.setItem('automata-lab-view-settings', JSON.stringify(viewSettings)); applyViewSettings(); }));
document.getElementById('openFile').addEventListener('change', event => { const file = event.target.files[0]; if (!file) return; const reader = new FileReader(); reader.onload = () => { try { const imported = JSON.parse(reader.result); if (!Array.isArray(imported.nodes) || !Array.isArray(imported.edges)) throw new Error('Invalid machine'); machines[activeMachine] = { ...machines[activeMachine], name: imported.name || machines[activeMachine].name, nodes: imported.nodes, edges: imported.edges, nodeCounter: imported.nodeCounter || imported.nodes.length, edgeCounter: imported.edgeCounter || imported.edges.length, alphabet: imported.alphabet || ['a', 'b'], testedResults: imported.testedResults || [] }; loadMachine(activeMachine); } catch (error) { window.alert('Could not open this file. Choose an Automata Lab JSON machine.'); } event.target.value = ''; }; reader.readAsText(file); });
const alphabetInput = document.getElementById('alphabetInput');
if (alphabetInput) alphabetInput.addEventListener('input', () => { renderFormal(); persistMachine(); });
let resizingPanel = null;
document.querySelectorAll('.panel-resizer').forEach(resizer => { resizer.addEventListener('pointerdown', event => { resizingPanel = resizer; resizer.classList.add('dragging'); event.preventDefault(); }); });
document.addEventListener('pointermove', event => { if (!resizingPanel) return; const rect = document.querySelector('.app-shell').getBoundingClientRect(); const width = resizingPanel.dataset.resize === 'left' ? Math.max(190, Math.min(390, event.clientX - rect.left)) : Math.max(250, Math.min(420, rect.right - event.clientX)); document.documentElement.style.setProperty(`--${resizingPanel.dataset.resize}-panel-width`, `${width}px`); });
document.addEventListener('pointerup', () => { if (resizingPanel) resizingPanel.classList.remove('dragging'); resizingPanel = null; });
document.getElementById('saveBtn').addEventListener('click', () => { persistMachine(); const file = new Blob([JSON.stringify({ name: machines[activeMachine].name, nodes, edges }, null, 2)], { type: 'application/json' }); const link = document.createElement('a'); link.href = URL.createObjectURL(file); const timestamp = new Date().toISOString().replace(/[T:]/g, '-').replace(/\.\d{3}Z$/, ''); link.download = `AutomataLab_${timestamp}.json`; link.click(); URL.revokeObjectURL(link.href); });
document.addEventListener('keydown', event => { const editingText = ['INPUT', 'TEXTAREA'].includes(document.activeElement?.tagName) || document.activeElement?.isContentEditable; if (event.ctrlKey && event.key.toLowerCase() === 'z') { if (!editingText) { event.preventDefault(); event.shiftKey ? redo() : undo(); } return; } if (event.ctrlKey && event.key.toLowerCase() === 'y') { if (!editingText) { event.preventDefault(); redo(); } return; } if (!editingText && (event.key === 'Delete' || event.key === 'Backspace') && selectedEdge) { edges = edges.filter(edge => edge.id !== selectedEdge); selectedEdge = null; render(); return; } if (!editingText && (event.key === 'Delete' || event.key === 'Backspace') && selectedNode) { nodes = nodes.filter(node => node.id !== selectedNode); edges = edges.filter(edge => edge.from !== selectedNode && edge.to !== selectedNode); selectedNode = null; render(); } if (event.key === 'Enter' && document.activeElement.id === 'inputString') runSimulation(); });
document.getElementById('resetBtn').addEventListener('click', () => { nodes = []; edges = []; selectedNode = null; nodeCounter = 0; edgeCounter = 0; simulation = null; defaultGraph(); clearTrace(); });
document.getElementById('zoomIn').addEventListener('click', () => changeZoom(.1)); document.getElementById('zoomOut').addEventListener('click', () => changeZoom(-.1));
function changeZoom(amount) { zoom = Math.max(.7, Math.min(1.3, zoom + amount)); document.getElementById('zoomLabel').textContent = `${Math.round(zoom * 100)}%`; svg.style.transform = `scale(${zoom})`; }
document.getElementById('simulateBtn').addEventListener('click', () => runSimulation());
document.getElementById('printBtn').addEventListener('click', () => document.getElementById('printDialog').showModal());
document.getElementById('closePrint').addEventListener('click', () => document.getElementById('printDialog').close());
document.getElementById('confirmPrint').addEventListener('click', () => { const checks = { machine: document.getElementById('printMachine').checked, definition: document.getElementById('printDefinition').checked, tests: document.getElementById('printTests').checked }; buildPrintOutput(checks); document.getElementById('printDialog').close(); generatePdf(checks); });
document.getElementById('printMeta').textContent = `Generated ${new Date().toLocaleString()}`;
document.getElementById('simulationTab').addEventListener('click', () => switchRightView('simulation'));
document.getElementById('definitionTab').addEventListener('click', () => switchRightView('definition'));
function switchRightView(view) { const simulationTab = document.getElementById('simulationTab'); const definitionTab = document.getElementById('definitionTab'); const simulationView = document.getElementById('simulationView'); const definitionView = document.getElementById('definitionView'); const definition = view === 'definition'; simulationTab.classList.toggle('active', !definition); definitionTab.classList.toggle('active', definition); simulationTab.setAttribute('aria-selected', String(!definition)); definitionTab.setAttribute('aria-selected', String(definition)); simulationView.hidden = definition; definitionView.hidden = !definition; }
document.querySelectorAll('.right-tab').forEach(tab => tab.addEventListener('click', () => { document.querySelectorAll('.right-tab').forEach(item => { item.classList.toggle('active', item === tab); item.setAttribute('aria-selected', item === tab ? 'true' : 'false'); }); document.querySelectorAll('.right-view').forEach(view => { const active = view.id === tab.dataset.panel; view.classList.toggle('active', active); view.hidden = !active; }); }));
document.getElementById('undoBtn').addEventListener('click', undo);
document.getElementById('redoBtn').addEventListener('click', redo);
const helpDialog = document.getElementById('helpDialog');
document.getElementById('helpLink').addEventListener('click', event => { event.preventDefault(); helpDialog.showModal(); });
document.getElementById('closeHelp').addEventListener('click', () => helpDialog.close());
helpDialog.addEventListener('click', event => { if (event.target === helpDialog) helpDialog.close(); });
const supportDialog = document.getElementById('supportDialog');
document.getElementById('supportLink').addEventListener('click', event => { event.preventDefault(); supportDialog.showModal(); });
document.getElementById('closeSupport').addEventListener('click', () => supportDialog.close());
supportDialog.addEventListener('click', event => { if (event.target === supportDialog) supportDialog.close(); });
function runSimulation(inputOverride = null, testRun = false) {
  const start = nodes.find(node => node.type === 'start'); const input = (inputOverride === null ? document.getElementById('inputString').value : inputOverride).trim(); const symbols = input ? (input.includes(' ') ? input.split(/\s+/) : [...input]) : [];
  if (!start) { showResult(false, 'No start state', 'Add a start state before simulating.'); return; }
  const steps = [{ symbol: 'START', states: [start.id], edges: [] }]; let current = epsilonClosure(new Set([start.id])).states;
  symbols.forEach(symbol => { const next = new Set(); const used = []; current.forEach(state => edges.filter(edge => edge.from === state && (edge.label === symbol || (edge.label === 'Σ' && getAlphabet().includes(symbol)))).forEach(edge => { next.add(edge.to); used.push(edge.id); })); const closed = epsilonClosure(next, used); current = closed.states; const acceptedStep = [...current].some(id => nodeById(id)?.type === 'accept'); const trappedStep = current.size > 0 && [...current].every(id => nodeById(id)?.type === 'trap'); steps.push({ symbol, states: [...current], edges: [...used, ...closed.edges], status: !current.size || trappedStep ? 'dead' : acceptedStep ? 'accepted' : 'running' }); });
  const accepted = [...current].some(id => nodeById(id)?.type === 'accept'); if (testRun) { testedResults.push({ input: input || 'epsilon', result: accepted ? 'Accepted' : 'Rejected', timestamp: new Date().toLocaleString() }); renderTestedResults(); persistMachine(); return accepted; } testedResults.push({ input: input || 'epsilon', result: accepted ? 'Accepted' : 'Rejected', timestamp: new Date().toLocaleString() }); simulation = { steps, activeStates: steps[0].states, activeEdges: [] }; render(); clearTrace(); showResult(accepted, accepted ? 'String accepted' : 'String rejected', accepted ? 'At least one path reached an accept state.' : 'No active path reached an accept state.'); steps.forEach((step, index) => { const row = document.createElement('div'); row.className = 'trace-row'; row.innerHTML = `<span class="trace-step">${String(index).padStart(2, '0')}</span><span class="trace-symbol">${step.symbol}</span><span class="trace-states">${step.states.length ? step.states.map(id => nodeById(id)?.label).join(', ') : 'dead end'}</span>`; row.addEventListener('click', () => showStep(index)); document.getElementById('traceList').appendChild(row); }); showStep(0); document.getElementById('stepCount').textContent = `0 / ${steps.length - 1}`;
  playTrace();
}
function epsilonClosure(states, suppliedEdges = []) { const result = new Set(states); const used = [...suppliedEdges]; let changed = true; while (changed) { changed = false; edges.filter(edge => edge.label === 'eps' && result.has(edge.from)).forEach(edge => { if (!result.has(edge.to)) { result.add(edge.to); used.push(edge.id); changed = true; } }); } return { states: result, edges: used }; }
function playTrace() { clearInterval(playbackTimer); let index = 0; playbackTimer = setInterval(() => { if (!simulation) { clearInterval(playbackTimer); return; } index += 1; if (index >= simulation.steps.length) { clearInterval(playbackTimer); return; } showStep(index); }, 700); }
function showStep(index) { if (!simulation) return; const step = simulation.steps[index]; simulation.activeStates = step.states; simulation.activeEdges = step.edges; simulation.activeStatus = step.status || 'running'; render(); [...document.querySelectorAll('.trace-row')].forEach((row, rowIndex) => { row.classList.toggle('current', rowIndex === index); row.classList.toggle('accepted', simulation.steps[rowIndex]?.status === 'accepted'); row.classList.toggle('dead', simulation.steps[rowIndex]?.status === 'dead'); }); document.getElementById('stepCount').textContent = `${index} / ${simulation.steps.length - 1}`; }
function clearTrace() { document.getElementById('traceList').innerHTML = ''; document.getElementById('stepCount').textContent = '0 / 0'; }
function renderTestedResults() { const target = document.getElementById('testedResults'); if (!target) return; target.innerHTML = testedResults.length ? `<div class="tested-heading">Test history</div>${testedResults.slice(-20).reverse().map(test => `<div class="tested-row ${test.result.toLowerCase()}"><span>${test.input}</span><strong>${test.result}</strong></div>`).join('')}` : ''; }
function buildPrintOutput(checks) { const output = document.getElementById('printOutput'); const diagram = document.getElementById('printDiagram'); diagram.innerHTML = ''; if (checks.machine) { const clone = document.getElementById('automataCanvas').cloneNode(true); clone.removeAttribute('aria-label'); clone.style.transform = ''; clone.querySelectorAll('.edge, .node').forEach(element => element.classList.remove('active', 'accepted', 'dead')); clone.querySelectorAll('.edge, .start-arrow').forEach(element => element.setAttribute('marker-end', 'url(#arrowhead)')); if (nodes.length) { const padding = 145; const minX = Math.max(0, Math.min(...nodes.map(node => node.x)) - padding); const minY = Math.max(0, Math.min(...nodes.map(node => node.y)) - padding); const maxX = Math.min(1000, Math.max(...nodes.map(node => node.x)) + padding); const maxY = Math.min(680, Math.max(...nodes.map(node => node.y)) + padding); clone.setAttribute('viewBox', `${minX} ${minY} ${Math.max(1, maxX - minX)} ${Math.max(1, maxY - minY)}`); clone.setAttribute('preserveAspectRatio', 'xMidYMid meet'); } diagram.appendChild(clone); } diagram.classList.toggle('selected', checks.machine); const definition = document.getElementById('printDefinitionOutput'); definition.innerHTML = checks.definition ? `<h2>Machine definition</h2><div class="print-formal">${document.getElementById('formalBlock').innerHTML}</div><h3>Transition table</h3>${document.getElementById('transitionTable').innerHTML}` : ''; definition.classList.toggle('selected', checks.definition); const tests = document.getElementById('printTestsOutput'); tests.innerHTML = checks.tests ? `<h2>Accepted and rejected tests</h2>${testedResults.length ? testedResults.map(test => `<div class="print-test-row"><span>${test.input}</span><strong class="${test.result.toLowerCase()}">${test.result}</strong><small>${test.timestamp}</small></div>`).join('') : '<p>No tests recorded yet. Run a simulation or generate test strings to create this list.</p>'}` : ''; tests.classList.toggle('selected', checks.tests); document.getElementById('printTimestampText').textContent = `Generated ${new Date().toLocaleString()}`; output.classList.toggle('selected', checks.machine || checks.definition || checks.tests); }
async function generatePdf(checks) { const timestamp = new Date().toISOString().replace(/[T:]/g, '-').replace(/\.\d{3}Z$/, ''); const output = document.getElementById('printOutput'); if (!window.jspdf?.jsPDF || !window.html2canvas) { document.body.className = `print-machine-${checks.machine} print-definition-${checks.definition} print-tests-${checks.tests}`; document.title = `AutomataLab_${timestamp}`; window.print(); setTimeout(() => { document.body.className = ''; document.title = 'Automata Lab'; }, 1000); return; } const originalStyle = output.getAttribute('style') || ''; output.classList.add('pdf-render'); output.style.display = 'block'; output.style.width = '794px'; output.style.background = '#fff'; const canvas = await window.html2canvas(output, { scale:2, backgroundColor:'#fff', logging:false }); const pdf = new window.jspdf.jsPDF({ orientation:'portrait', unit:'mm', format:'a4' }); const pageWidth = 210, pageHeight = 297, margin = 12, imageWidth = pageWidth - margin * 2, maxSliceHeight = pageHeight - margin * 2, pixelsPerMm = canvas.width / imageWidth, slicePixels = Math.floor(maxSliceHeight * pixelsPerMm); let sourceY = 0; while (sourceY < canvas.height) { const currentPixels = Math.min(slicePixels, canvas.height - sourceY); const currentHeight = currentPixels / pixelsPerMm; const pageCanvas = document.createElement('canvas'); pageCanvas.width = canvas.width; pageCanvas.height = currentPixels; pageCanvas.getContext('2d').drawImage(canvas, 0, sourceY, canvas.width, currentPixels, 0, 0, canvas.width, currentPixels); pdf.addImage(pageCanvas, 'PNG', margin, margin, imageWidth, currentHeight, undefined, 'FAST'); sourceY += currentPixels; if (sourceY < canvas.height) pdf.addPage(); } pdf.save(`AutomataLab_${timestamp}.pdf`); output.classList.remove('pdf-render'); output.setAttribute('style', originalStyle); }
function showResult(accepted, title, detail) { const panel = document.getElementById('resultPanel'); panel.className = `result-panel ${title === 'String accepted' ? 'accepted' : title === 'String rejected' ? 'rejected' : ''}`; panel.innerHTML = `<span class="result-icon">${title === 'String accepted' ? '&#10003;' : title === 'String rejected' ? '&#10005;' : '?'}</span><div><strong>${title}</strong><small>${detail}</small></div>`; }
function renderFormal() { const formal = document.getElementById('formalBlock'); const table = document.getElementById('transitionTable'); if (!formal || !table) return; const stateNames = nodes.map(node => node.label).join(', ') || '-'; const alphabet = getAlphabet().join(', ') || '-'; const start = nodes.find(node => node.type === 'start')?.label || '-'; const accepts = nodes.filter(node => node.type === 'accept').map(node => node.label).join(', ') || '-'; const formula = edges.length ? edges.map(edge => `delta(${nodeById(edge.from)?.label || '-'}, ${edge.label}) = { ${nodeById(edge.to)?.label || '-'} }`).join('\n') : 'delta(q, a) = { }'; formal.innerHTML = `<div>M = (Q, Sigma, delta, q0, F)</div><div>Q = { ${stateNames} }</div><div>Sigma = { ${alphabet} }</div><div>delta =</div><div class="formula-lines">${formula}</div><div>q0 = ${start}</div><div>F = { ${accepts} }</div>`; table.innerHTML = nodes.length ? `<table><thead><tr><th>State</th><th>Symbol</th><th>Next</th></tr></thead><tbody>${edges.map(edge => `<tr><td>${nodeById(edge.from)?.label || '-'}</td><td>${edge.label}</td><td>${nodeById(edge.to)?.label || '-'}</td></tr>`).join('')}</tbody></table>` : '<span class="muted">No transitions yet.</span>'; }
function renderMachineType() { const panel = document.getElementById('machineType'); const toast = document.getElementById('machineToast'); if (!panel || !toast) return; if (!nodes.length) { panel.className = 'machine-type empty'; panel.innerHTML = '<span class="machine-type-dot"></span><strong>Empty machine</strong><small>add states to classify</small>'; toast.className = 'machine-toast empty'; toast.innerHTML = '<span class="machine-toast-dot"></span><div><strong>Empty machine</strong><small>add states to classify</small></div>'; return; } const reasons = []; const epsilonEdge = edges.find(edge => edge.label === 'eps'); if (epsilonEdge) reasons.push('epsilon transition'); const grouped = new Map(); edges.forEach(edge => { const key = `${edge.from}:${edge.label}`; if (!grouped.has(key)) grouped.set(key, new Map()); grouped.get(key).set(edge.to, edge); }); grouped.forEach((destinations, key) => { if (destinations.size > 1) { const first = [...destinations.values()][0]; reasons.push(`${nodeById(first.from)?.label || first.from} has multiple destinations for input ${first.label}`); } }); const wildcardSources = new Set(); edges.filter(edge => edge.label === 'Σ').forEach(edge => { if (edges.some(other => other.from === edge.from && other.id !== edge.id && other.label !== 'eps' && other.label !== 'Σ')) wildcardSources.add(edge.from); }); wildcardSources.forEach(source => reasons.push(`${nodeById(source)?.label || source} has overlapping Sigma input`)); const isDfa = reasons.length === 0; const detail = isDfa ? 'deterministic machine' : reasons.map(reason => `<span class="machine-report">${reason}</span>`).join(''); panel.className = `machine-type ${isDfa ? 'dfa' : 'nfa'}`; panel.innerHTML = `<span class="machine-type-dot"></span><strong>${isDfa ? 'DFA' : 'NFA'}</strong><small>${detail}</small>`; toast.className = `machine-toast ${isDfa ? 'dfa' : 'nfa'}`; toast.innerHTML = `<span class="machine-toast-dot"></span><div><strong>${isDfa ? 'DFA' : 'NFA'}</strong><small>${detail}</small></div>`; }
document.getElementById('generateBtn').addEventListener('click', () => { const alphabet = getAlphabet(); const length = Math.max(0, Math.min(8, Number(document.getElementById('maxLengthInput').value) || 0)); const total = Array.from({ length: length + 1 }, (_, power) => alphabet.length ** power).reduce((sum, count) => sum + count, 0); if (!alphabet.length) { document.getElementById('generatorNote').textContent = 'Define at least one alphabet symbol first.'; return; } if (total > 1000 && !window.confirm(`This will test ${total.toLocaleString()} strings. Large runs may take time. Continue?`)) return; testedResults = []; const generate = (prefix, remaining) => { if (remaining === 0) { runSimulation(prefix, true); return; } alphabet.forEach(symbol => generate(prefix + symbol, remaining - 1)); }; for (let size = 0; size <= length; size += 1) generate('', size); document.getElementById('generatorNote').textContent = `Generated ${total.toLocaleString()} tests.`; renderTestedResults(); });
render();
